
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Calendar calendar2;

	private global::Gtk.Calendar calendar3;

	private global::Gtk.Button button1;

	private global::Gtk.Alignment alignment1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Flights");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-zoom-fit", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendar2 = new global::Gtk.Calendar();
		this.calendar2.CanFocus = true;
		this.calendar2.Name = "calendar2";
		this.calendar2.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add(this.calendar2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.calendar2]));
		w1.X = 15;
		w1.Y = 11;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendar3 = new global::Gtk.Calendar();
		this.calendar3.CanFocus = true;
		this.calendar3.Name = "calendar3";
		this.calendar3.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add(this.calendar3);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.calendar3]));
		w2.X = 250;
		w2.Y = 8;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Search");
		this.fixed1.Add(this.button1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
		w3.X = 515;
		w3.Y = 23;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.fixed1.Add(this.alignment1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.alignment1]));
		w4.X = 370;
		w4.Y = 268;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.WidthRequest = 1200;
		this.GtkScrolledWindow.HeightRequest = 500;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add(this.textview1);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w6.X = 15;
		w6.Y = 200;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1264;
		this.DefaultHeight = 733;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.calendar2.PrevMonth += new global::System.EventHandler(this.OnCalendar2PrevMonth);
		this.calendar2.DaySelected += new global::System.EventHandler(this.OnCalendar2DaySelected);
		this.calendar2.NextMonth += new global::System.EventHandler(this.OnCalendar2NextMonth);
		this.calendar2.MonthChanged += new global::System.EventHandler(this.OnCalendar2MonthChanged);
		this.calendar2.PrevYear += new global::System.EventHandler(this.OnCalendar2PrevYear);
		this.calendar2.NextYear += new global::System.EventHandler(this.OnCalendar2NextYear);
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
	}
}
